import {parseCSV,profile,clean,csv,sample,blank} from './core.mjs';
import {readWorkbook,writeWorkbook} from './xlsx.mjs';
const $=id=>document.getElementById(id);let source=null,result=null,workbook=null,name='',view='original';
function message(t=''){$('message').textContent=t;}
function options(){return {trim:$('trim').checked,empty:$('empty').checked,duplicates:$('duplicates').checked};}
function invalidate(){result=null;view='original';$('downloads').hidden=true;$('result').hidden=true;$('cleaned').disabled=true;render();}
function load(data,label){source=data;name=label;for(const id of ['trim','empty','duplicates'])$(id).checked=false;$('workspace').hidden=false;$('empty-state').hidden=true;$('filename').textContent=label;$('filemeta').textContent=`${data.rows.length.toLocaleString()} rows · ${data.headers.length} columns`;invalidate();}
function render(){if(!source)return;const data=view==='cleaned'&&result?result.data:source,p=profile(data);$('stats').replaceChildren();for(const [label,value,detail,warn]of [['Rows',p.rows,'in this view',false],['Columns',p.columns,'fields',false],['Missing cells',p.missing,'need review',p.missing>0],['Duplicate rows',p.duplicates,'exact matches',p.duplicates>0]]){let el=document.createElement('div');el.className='stat'+(warn?' warn':'');let s=document.createElement('small');s.textContent=label;let v=document.createElement('strong');v.textContent=value.toLocaleString();let e=document.createElement('em');e.textContent=detail;v.append(e);el.append(s,v);$('stats').append(el);}
 const table=$('table');table.replaceChildren();let head=document.createElement('thead'),tr=document.createElement('tr');for(const h of ['#',...data.headers]){let th=document.createElement('th');th.textContent=h;tr.append(th);}head.append(tr);table.append(head);let body=document.createElement('tbody');for(const [i,row]of data.rows.slice(0,100).entries()){let r=document.createElement('tr'),num=document.createElement('td');num.textContent=i+1;r.append(num);for(const value of row){let td=document.createElement('td');td.textContent=blank(value)?'—':value;td.title=blank(value)?'Missing value':value;if(blank(value))td.className='missing';else if(value!==value.trim())td.className='whitespace';r.append(td);}body.append(r);}table.append(body);$('table-count').textContent=`Showing ${Math.min(100,data.rows.length)} of ${data.rows.length.toLocaleString()} rows`;for(const id of ['original','cleaned'])$(id).setAttribute('aria-selected',String(view===id));$('columns').replaceChildren();for(const c of p.byColumn){let el=document.createElement('div'),top=document.createElement('div'),strong=document.createElement('strong'),span=document.createElement('span'),bar=document.createElement('div'),fill=document.createElement('i');top.className='column-top';strong.textContent=c.name;span.textContent=`${c.missing} missing · ${c.unique} unique`;top.append(strong,span);bar.className='bar';fill.style.width=(p.rows?(p.rows-c.missing)/p.rows*100:0)+'%';bar.append(fill);el.append(top,bar);$('columns').append(el);}}
function preview(){if(!source)throw Error('Load a file first.');result=clean(source,options());view='cleaned';$('cleaned').disabled=false;$('downloads').hidden=false;$('result').hidden=false;$('result').textContent=`${result.changedCells} cells trimmed · ${result.removedRows} rows removed. ${result.data.rows.length} rows kept. Original data preserved.`;render();return {before:profile(source),after:profile(result.data),changes:result.changes.length};}
function download(blob,filename){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000);}
const stem=()=>name.replace(/\.[^.]+$/,'');
$('sample').onclick=()=>{workbook=null;$('sheet-control').hidden=true;message('Sample data is fictional. Try the cleaning rules to see the difference.');load(structuredClone(sample),'sample-orders.csv');};
async function openFile(file){if(!file)return;message();try{if(file.size>5*1024*1024)throw Error('Please choose a file smaller than 5 MB.');if(!/\.(csv|tsv|xlsx)$/i.test(file.name))throw Error('Choose a CSV, TSV, or XLSX file. Legacy .xls files are not supported.');if(/\.xlsx$/i.test(file.name)){workbook=await readWorkbook(await file.arrayBuffer());$('sheet').replaceChildren();workbook.names.forEach((n,i)=>{let o=document.createElement('option');o.value=i;o.textContent=n;$('sheet').append(o);});const parsed=workbook.sheet(0);load(parsed.data,file.name);$('sheet-control').hidden=false;message('Excel imported as values only. Dates may appear as serial numbers; formulas use saved results. No formatting is retained.');}else{workbook=null;load(parseCSV(await file.text()),file.name);$('sheet-control').hidden=true;}}catch(e){message(e.message);}finally{$('file').value='';}}
$('file').onchange=e=>openFile(e.target.files[0]);$('sheet').onchange=()=>{try{load(workbook.sheet(Number($('sheet').value)).data,name);}catch(e){message(e.message);}};
for(const event of ['dragenter','dragover'])$('drop').addEventListener(event,e=>{e.preventDefault();$('drop').classList.add('dragging');});for(const event of ['dragleave','drop'])$('drop').addEventListener(event,e=>{e.preventDefault();$('drop').classList.remove('dragging');});$('drop').addEventListener('drop',e=>openFile(e.dataTransfer.files[0]));
for(const id of ['trim','empty','duplicates'])$(id).onchange=invalidate;
$('apply').onclick=preview;for(const id of ['original','cleaned'])$(id).onclick=()=>{view=id;render();};
$('download-csv').onclick=()=>download(new Blob([csv(result.data)],{type:'text/csv;charset=utf-8'}),stem()+'-cleaned.csv');$('download-xlsx').onclick=()=>download(writeWorkbook(result.data),stem()+'-cleaned.xlsx');$('download-report').onclick=()=>download(new Blob([JSON.stringify({file:name,worksheet:workbook?workbook.names[Number($('sheet').value)]:null,rules:options(),before:profile(source),after:profile(result.data),changes:result.changes},null,2)],{type:'application/json'}),stem()+'-report.json');
$('reset').onclick=()=>{source=null;result=null;workbook=null;$('workspace').hidden=true;$('sheet-control').hidden=true;$('empty-state').hidden=false;message();};
const picker=document.querySelector('label[for="file"]');picker.setAttribute('tabindex','0');picker.setAttribute('role','button');picker.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('file').click();}});
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});for(const tool of [
 {name:'load_sample_dataset',description:'Load the fictional orders sample into the visible workspace. Replaces the current local dataset.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(){ $('sample').click();return profile(source);}},
 {name:'inspect_dataset',description:'Read the current dataset quality counts. Does not include cell contents.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){if(!source)throw Error('No dataset loaded');return {original:profile(source),cleaned:result?profile(result.data):null};}},
 {name:'preview_cleaning',description:'Select cleaning rules and preview the result without changing the original or downloading a file.',inputSchema:{type:'object',properties:{trim:{type:'boolean'},empty:{type:'boolean'},duplicates:{type:'boolean'}},required:['trim','empty','duplicates'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!source)throw Error('No dataset loaded');if(!input||Object.keys(input).some(k=>!['trim','empty','duplicates'].includes(k))||['trim','empty','duplicates'].some(k=>typeof input[k]!=='boolean'))throw Error('Three boolean rules are required');for(const id of ['trim','empty','duplicates'])$(id).checked=input[id];return preview();}}
 ]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}}
