import {normalize} from './core.mjs';
const enc=new TextEncoder(),dec=new TextDecoder();
function xml(s){const d=new DOMParser().parseFromString(s,'application/xml');if(d.getElementsByTagName('parsererror').length)throw Error('Invalid Excel XML.');return d;}
function text(node,tag){return Array.from(node.getElementsByTagName(tag)).map(n=>n.textContent).join('');}
async function unzip(buffer){const view=new DataView(buffer),bytes=new Uint8Array(buffer);let end=bytes.length-22;while(end>=Math.max(0,bytes.length-65557)&&view.getUint32(end,true)!==0x06054b50)end--;if(end<0)throw Error('Not a valid .xlsx file.');let count=view.getUint16(end+10,true),offset=view.getUint32(end+16,true),files=new Map(),total=0;if(count>5000)throw Error('Workbook has too many internal files.');for(let i=0;i<count;i++){if(view.getUint32(offset,true)!==0x02014b50)throw Error('Invalid workbook directory.');let method=view.getUint16(offset+10,true),size=view.getUint32(offset+20,true),expanded=view.getUint32(offset+24,true),nl=view.getUint16(offset+28,true),xl=view.getUint16(offset+30,true),cl=view.getUint16(offset+32,true),loc=view.getUint32(offset+42,true),name=dec.decode(bytes.slice(offset+46,offset+46+nl));total+=expanded;if(total>50*1024*1024)throw Error('Expanded workbook exceeds the 50 MB limit.');if(name.endsWith('.xml')||name.endsWith('.rels')){let start=loc+30+view.getUint16(loc+26,true)+view.getUint16(loc+28,true),raw=bytes.slice(start,start+size);if(method===8){const stream=new Blob([raw]).stream().pipeThrough(new DecompressionStream('deflate-raw'));raw=new Uint8Array(await new Response(stream).arrayBuffer());}else if(method!==0)throw Error('Unsupported workbook compression.');files.set(name,dec.decode(raw));}offset+=46+nl+xl+cl;}return files;}
export async function readWorkbook(buffer){const files=await unzip(buffer),work=xml(files.get('xl/workbook.xml')||''),rels=xml(files.get('xl/_rels/workbook.xml.rels')||''),shared=files.has('xl/sharedStrings.xml')?Array.from(xml(files.get('xl/sharedStrings.xml')).getElementsByTagName('si')).map(n=>text(n,'t')):[];
 const sheets=Array.from(work.getElementsByTagName('sheet')).map(s=>{const id=s.getAttribute('r:id'),rel=Array.from(rels.getElementsByTagName('Relationship')).find(r=>r.getAttribute('Id')===id),target=rel?.getAttribute('Target')||'';const path=target.startsWith('/')?target.slice(1):'xl/'+target.replace(/^\.\//,'');return {name:s.getAttribute('name'),path};});
 return {names:sheets.map(s=>s.name),sheet(index){const s=sheets[index];if(!s||!files.has(s.path))throw Error('Worksheet could not be read.');const doc=xml(files.get(s.path));let rows=[],formulas=0;for(const row of doc.getElementsByTagName('row')){const ri=Number(row.getAttribute('r'))-1;if(ri>20000)throw Error('Sheet exceeds 20,000 data rows.');while(rows.length<=ri)rows.push([]);for(const c of row.getElementsByTagName('c')){const letters=(c.getAttribute('r')||'A').replace(/[0-9]/g,'');let ci=0;for(const l of letters)ci=ci*26+l.charCodeAt(0)-64;ci--;if(ci>199)throw Error('Sheet exceeds 200 columns.');if(c.getElementsByTagName('f').length)formulas++;let v=text(c,'v');if(c.getAttribute('t')==='s')v=shared[Number(v)]??'';else if(c.getAttribute('t')==='inlineStr')v=text(c,'t');else if(c.getAttribute('t')==='b')v=v==='1'?'TRUE':'FALSE';rows[ri][ci]=v;}}return {data:normalize(rows),formulas};}};
}
const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g,'');
function crc32(a){let c=0xffffffff;for(const b of a){c^=b;for(let j=0;j<8;j++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function zip(entries){let parts=[],central=[],offset=0;for(const [name,str]of entries){let n=enc.encode(name),d=enc.encode(str),crc=crc32(d),h=new Uint8Array(30+n.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint32(14,crc,true);v.setUint32(18,d.length,true);v.setUint32(22,d.length,true);v.setUint16(26,n.length,true);h.set(n,30);parts.push(h,d);let ch=new Uint8Array(46+n.length),cv=new DataView(ch.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint32(16,crc,true);cv.setUint32(20,d.length,true);cv.setUint32(24,d.length,true);cv.setUint16(28,n.length,true);cv.setUint32(42,offset,true);ch.set(n,46);central.push(ch);offset+=h.length+d.length;}const size=central.reduce((s,c)=>s+c.length,0),end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,entries.length,true);ev.setUint16(10,entries.length,true);ev.setUint32(12,size,true);ev.setUint32(16,offset,true);ev.setUint32(0,0x06054b50,true);return new Blob([...parts,...central,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});}
export function writeWorkbook(data){const col=i=>{let s='';for(i++;i;i=Math.floor((i-1)/26))s=String.fromCharCode(65+(i-1)%26)+s;return s;};const cols=data.headers.map((h,i)=>`<col min="${i+1}" max="${i+1}" width="${Math.min(48,Math.max(14,...[h,...data.rows.map(r=>r[i])].map(v=>String(v??'').length+2)))}" customWidth="1"/>`).join('');const rows=[data.headers,...data.rows].map((r,i)=>`<row r="${i+1}">${r.map((v,j)=>`<c r="${col(j)}${i+1}" t="inlineStr"><is><t xml:space="preserve">${escape(v)}</t></is></c>`).join('')}</row>`).join('');return zip([['[Content_Types].xml','<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'],['_rels/.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],['xl/workbook.xml','<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Cleaned data" sheetId="1" r:id="rId1"/></sheets></workbook>'],['xl/_rels/workbook.xml.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'],['xl/worksheets/sheet1.xml',`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><cols>${cols}</cols><sheetData>${rows}</sheetData></worksheet>`]]);}
